### ISSUE TITLE
Squid does not restart properly

### ISSUE THREAD

**Issue by huangchao-shanghai** [b4tman/docker-squid#104]
When I use the command 'docker restart squid8012-edge' to restart the containers, Squid does not restart properly and this error occurs.
Is there a configuration error? Please advise, thank you.

```
squid8012-edge  | 2023/07/06 19:16:46| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| Processing Configuration File: /etc/squid/squid.conf (depth 0)
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| Created PID file (/var/run/squid/squid.pid)
squid8012-edge  | 2023/07/06 19:16:46 kid1| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46 kid1| Processing Configuration File: /etc/squid/squid.conf (depth 0)
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46 kid1| Set Current Directory to /var/spool/squid
squid8012-edge  | 2023/07/06 19:16:46 kid1| Creating missing swap directories
squid8012-edge  | 2023/07/06 19:16:46 kid1| No cache_dir stores are configured.
squid8012-edge  | 2023/07/06 19:16:46| Removing PID file (/var/run/squid/squid.pid)
squid8012-edge  | 2023/07/06 19:16:46| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| Processing Configuration File: /etc/squid/squid.conf (depth 0)
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| aclIpParseIpData: IPv6 has not been enabled.
squid8012-edge  | 2023/07/06 19:16:46| Created PID file (/var/run/squid/squid.pid)
squid8012-edge  | 2023/07/06 19:16:46 kid1| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
squid8012-edge  | 2023/07/06 19:16:46 kid1| aclIpParseIpData: IPv6 has not been enabled.
```

#docker compose file
```
  squid8012-edge:
    image: b4tman/squid:v6
    container_name: squid8012-edge
    ports:
      - "3128:3128"
    volumes:
      - /docker-data/squid8012-edge/etc/squid/squid.conf:/etc/squid/squid.conf
      - /docker-data/squid8012-edge/etc/squid/ssl:/etc/squid/ssl
      - /docker-data/squid8012-edge/var/spool/squid:/var/spool/squid
      - /docker-data/squid8012-edge/var/logs/squid:/var/log/squid
    environment:
      - TZ=Asia/Shanghai
    networks:
      squid_network:
        ipv4_address: 172.16.0.212
    restart: always

```
![image](https://github.com/b4tman/docker-squid/assets/3233883/d164766b-5e05-43f4-90ca-481ca7610ddd)
